In [2]:
import numpy as np

##creating array from list

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ",arr_1d)

# arr_2d = np.array([1,2,3],[4,5,6]) # there are two array
arr_2d = np.array([[1,2,3],[4,5,6]]) # there are two array inside another array
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


##List vs Nunpy Array

In [ ]:
py_list = [1,2,3]
print("python muliplication:",py_list * 3)

np_array = np.array((1,2,3)) #element wise multiplication
print("python arry(numpy) muliplication:",np_array * 3)



import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\nList operation time:",time.time()-start)

start = time.time()
np_array = np.arange(100000) * 2 # "arange" works similar to "range" in for loop
print("\nNumpy operation time:",time.time()-start)

python muliplication: [1, 2, 3, 1, 2, 3, 1, 2, 3]
python arry(numpy) muliplication: [3 6 9]

List operation time: 0.008912324905395508

Numpy operation time: 0.0016002655029296875


##Creating array from scratch

In [ ]:
from typing import Sequence
zeros = np.zeros((3,4))
print("zero array:\n",zeros)

ones = np.ones((2,3)) # value inside is order of matrix
print("\nones array:\n",ones)

full = np.full((2,2),7) # array with 2x2 order with elemrnt 7
print("\nfull array:\n",full)


random = np.random.random((2,3))
print("\nransom array:\n",random)

Sequence = np.arange(0,10,2) # start, stop, step
print("\nSequence array:\n",Sequence)


zero array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]

full array:
 [[7 7]
 [7 7]]

ransom array:
 [[0.09036493 0.17257917 0.33059174]
 [0.55665892 0.13476871 0.78095764]]

Sequence array:
 [0 2 4 6 8]



##Vector, Matrix, Tenor

In [ ]:
vector = np.array([1,2,3])
print("vetctor:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("\nmatrix:",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[6,8]]])
print("\ntensor:",tensor)

vetctor: [1 2 3]

matrix: [[1 2 3]
 [4 5 6]]

tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [6 8]]]


##Array properties

In [10]:
arr = np.array([[1,2,3],
              [4,5,6]])

print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("DataType",arr.dtype)


arr2 = np.array([[1,2,3],
              [4,5,6.4]]) #float value here
print("\nShape",arr2.shape)
print("Dimension",arr2.ndim)
print("Size",arr2.size)
print("DataType",arr2.dtype)


arr3 = np.array([[1,2,3],
              [4,5,"6.4"]])
print("\nDataType",arr3.dtype)


Shape (2, 3)
Dimension 2
Size 6
DataType int64

Shape (2, 3)
Dimension 2
Size 6
DataType float64

DataType <U21


##Array Reshaping

In [18]:
arr = np.arange(12)
print("Original array",arr)

reshaped = arr.reshape((3,4))# converts arr into 3x4 matrix
print("\nReshaped array:",reshaped)

#rerns copy of an array
flatten = reshaped.flatten()
print("\nFlatten array:",flatten)

#returns view instead of copy(unlike flatten())
raveled = reshaped.ravel()
print("\nRaveled array:",raveled)


#Transpose
transpose = reshaped.T
print("\nTranspose array:",transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flatten array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
