##NumPy Array operaions

In [1]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("baic slicing:",arr[2:7])
print("with steps:",arr[1:8:2])
print("Negative indexing:",arr[-3]) #last third index

baic slicing: [3 4 5 6 7]
with steps: [2 4 6 8]
Negative indexing: 8


In [ ]:
arr_2d = np.array([[1,2,3],#0th row
                   [4,5,6],#1st row
                  [7,8,9]])#2nd row
print("spesific element:",arr_2d[1, 2]) # row, column
print("Entire row:",arr_2d[1])
print("Entire column:",arr_2d[:,1])#first column

spesific element: 6
Entire row: [4 5 6]
Entire column: [2 5 8]


##Sorting


In [ ]:
unsorted = np.array([3,1,5,7,3,5,9,6,54,66])
print("\nsorted array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("\nsorted 2d array by row:",np.sort(arr_2d_unsorted,axis=0))
print("\nsorted 2d array by column:",np.sort(arr_2d_unsorted,axis=1))



sorted array: [ 1  3  3  5  5  6  7  9 54 66]

sorted 2d array by row: [[1 1]
 [2 2]
 [3 3]]

sorted 2d array by column: [[1 3]
 [1 2]
 [2 3]]


##Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] # for even numbers
print("even numbers: ",even_number)

even numbers:  [ 2  4  6  8 10]


##Filter with mask

In [6]:
# numbers = np.array([1,2,3,4,5,6,7,8,9,10])
mask = numbers > 5
print("Number greater than 5:",numbers[mask])

Number greater than 5: [ 6  7  8  9 10]


##Fansy indexing vs np.where()

In [7]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5) #stores indexing of array
print(where_result)
print("np where:",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
np where: [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, numbers*2, numbers) #(condition, x val, y val)
print(condition_array)

condition_array1 = np.where(numbers > 5, numbers*1, numbers) #(condition, x val, y val)
print(condition_array1)

condition_array2 = np.where(numbers > 5, numbers, numbers) #(condition, x val, y val)
print(condition_array2)

condition_array3 = np.where(numbers > 5, "true", "false") #(condition, x val, y val)
print(condition_array3)


# for understanging
# it works someting like this
# if(numbers > 5){
#     numbers * 3
# }else{
#     number
# }

[ 1  2  3  4  5 12 14 16 18 20]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


##Adding and removing data

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# combined = arr1 + arr2
# print(combined) #does a matrix addition

combined = np.concatenate((arr1,arr2)) # takes tupple as input "(arr1,arr2)"
print(combined)



[1 2 3 4 5 6]


##Array compatiblity

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatiblity shapes:",a.shape == b.shape)
print("Compatiblity shapes:",a.shape == c.shape)


Compatiblity shapes: False
Compatiblity shapes: True


In [18]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row)) #vtack = vertical stack
print(with_new_row)


new_column = np.array([[7],[8]])
with_new_column = np.hstack((original, new_column)) #htack = horizontal stack
print("\n",with_new_column)


[[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


##Delete


In [22]:
arr = np.array([1,2,3])
delete = np.delete(arr, 2) #(array_name, start, stop, step)
print("array after deletion",delete)

array after deletion [1 2]
